feature: 20250911_offline_all_magnitudes
binary: false
window_limit: [20, 120]
desc: "semilla común 1111"
seeds: [1111, 99992,2222,3333]
accel: false
global_feat: true
response: "vel"
patience: 200
lr: 0.00015
epochs: 2000
batch_size: 1
umbral_corte: 0
filter:
  - highpass
  - 0.1
dummy: false
use_cnn_model: true
use_cnn_features: false
regression: true
coast: false
left_right: false
softmax: false

include_env: false
include_lat_lon: false
include_index: false
include_magnitude: false
norm_energy: false
concat_features: false
log_scale: false
square_fft: false
include_p_vector: true 
n_energy_frames: 2
how_to_include_p: 3
use_module_p: true